const { createProxyMiddleware } = require('http-proxy-middleware');

module.exports = function (app) {
    // const LINK = 'https://localhost:3009';
    const LINK = 'https://css.niso.com.vn:3008/';
    app.post('/login/dashboard', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/users/all', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.post('/users/upload', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/users/download', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.post('/question/custom/add', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.post('/users/add', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.put('/users/update/:keys', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.delete('/users/delete/:keys', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.post('/css/add', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/css/all', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/chinhanh/all', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.post('/chinhanh/add', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.put('/chinhanh/update/:id', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.delete('/chinhanh/delete/:id', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.post('/chinhanh/upload', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/chinhanh/download', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.put('/question/edit/:id', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/question/all', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/question/download', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.post('/question/upload', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/question/brand/:brandName/step/:step', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/question/brand/:brandName', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.delete('/question/brand/:brandName/:id', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/question/thankyou', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.post('/question/thankyou', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/question/combined', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/visit/check/:ip', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.post('/visit/add', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/visit/count', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.put('/question/custom/:id', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/question/translations', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/api-config/get', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/api-config/list', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.post('/api-config/save', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.post('/api-config/save-draft', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.put('/api-config/:id', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.delete('/api-config/:id', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/questions/:brandName', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.post('/api-config/post-data', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.post('/views/add', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/views/:id', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/views/all', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.delete('/views/:id', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    // Form lưu trữ endpoints
    app.get('/question/storage/list', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/question/storage/list/brand-branch', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.post('/question/storage/add', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.delete('/question/storage/:id', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.put('/question/storage/:id', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.get('/question/steps/:questionId', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.put('/question/steps/:questionId', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.post('/question/storage/copy-steps', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
    app.put('/usersAccount/updateFormName', createProxyMiddleware({ target: LINK, changeOrigin: true, secure: false }));
};
